from fastapi import FastAPI, HTTPException, status
from database import init_db, get_db_connection
from models import TodoCreate

app = FastAPI()

init_db()

def row_to_dict(row):
    return {
        "id": row["id"],
        "title": row["title"],
        "completed": bool(row["completed"])
    }

@app.get("/todos", status_code=status.HTTP_200_OK)
def get_all_todos():
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM tasks")
    rows = cursor.fetchall()
    conn.close()
    return [row_to_dict(row) for row in rows]

@app.get("/todos/{todo_id}", status_code=status.HTTP_200_OK)
def get_todo(todo_id: int):
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM tasks WHERE id = ?", (todo_id,))
    row = cursor.fetchone()
    conn.close()
    
    if not row:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, 
            detail="Todo not found"
        )
    
    return row_to_dict(row)

@app.post("/todos", status_code=status.HTTP_201_CREATED)
def create_todo(todo: TodoCreate):
    conn = get_db_connection()
    cursor = conn.cursor()
    
    
    cursor.execute(
        "INSERT INTO tasks (title, completed) VALUES (?, ?)",
        (todo.title, todo.completed)
    )
    conn.commit()
    
    # Get the ID generated by SQLite
    new_id = cursor.lastrowid
    

    cursor.execute("SELECT * FROM tasks WHERE id = ?", (new_id,))
    new_task = cursor.fetchone()
    conn.close()
    
    return row_to_dict(new_task)


@app.put("/todos/{todo_id}", status_code=status.HTTP_200_OK)
def update_todo(todo_id: int, updated_todo: TodoCreate):
    conn = get_db_connection()
    cursor = conn.cursor()
    
    # Check if task exists first
    cursor.execute("SELECT * FROM tasks WHERE id = ?", (todo_id,))
    row = cursor.fetchone()
    if not row:
        conn.close()
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, 
            detail="Todo not found"
        )
    
    cursor.execute(
        "UPDATE tasks SET title = ?, completed = ? WHERE id = ?",
        (updated_todo.title, updated_todo.completed, todo_id)
    )
    conn.commit()
    
    cursor.execute("SELECT * FROM tasks WHERE id = ?", (todo_id,))
    updated_task = cursor.fetchone()
    conn.close()
    
    return row_to_dict(updated_task)


@app.delete("/todos/{todo_id}", status_code=status.HTTP_200_OK)
def delete_todo(todo_id: int):
    conn = get_db_connection()
    cursor = conn.cursor()
    
    
    cursor.execute("SELECT * FROM tasks WHERE id = ?", (todo_id,))
    row = cursor.fetchone()
    if not row:
        conn.close()
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, 
            detail="Todo not found"
        )
    
    # Delete the record
    cursor.execute("DELETE FROM tasks WHERE id = ?", (todo_id,))
    conn.commit()
    conn.close()
    
    return {"message": "Todo deleted successfully"}